<?php

/**
 * @file
 * Theme functions for the Kingly theme.
 */

/**
 * Implements hook_preprocess_html().
 */
function kingly_theme_preprocess_html(&$variables) {

  // Get the theme settings.
  $theme_settings = \Drupal::config('kingly_theme.settings');

  if (empty($theme_settings)) {
    return;
  }

  // Add the class to the body.
  $variables['attributes']['class'][] = $theme_settings->get('nl_design_system_theme_css_name') ?? 'nl-theme';
}
